using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ders2App.Models
{

    //make it static 
    public static class DbInitializer
    {
        public static void Seed(AppDbContext context)
        {
            if (!context.Books.Any())
            {
                context.AddRange
                (
                     new Book { Name = "Refactoring", Price = 10.95M, ShortDescription = "Refactoring", LongDescription = "Even bad code can function. But if code isn’t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn’t have to be that way. Noted software expert Robert C.Martin presents a revolutionary paradigm with Clean Code: A Handbook of Agile Software Craftsmanship.Martin has teamed up with his colleagues from Object Mentor to distill their best agile practice of cleaning code “on the fly” into a book that will instill within you the values of a software craftsman and make you a better programmer—but only if you work at it.", IsBookOfTheWeek = true, ImageThumbnailUrl = "https://www.safaribooksonline.com/library/cover/9780134757681/360h/" },

                    new Book { Name = "Clean Code", Price = 20.95M, ShortDescription = "Our Refactoring Book!", LongDescription = "Even bad code can function. But if code isn’t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn’t have to be that way. Noted software expert Robert C.Martin presents a revolutionary paradigm with Clean Code: A Handbook of Agile Software Craftsmanship.Martin has teamed up with his colleagues from Object Mentor to distill their best agile practice of cleaning code “on the fly” into a book that will instill within you the values of a software craftsman and make you a better programmer—but only if you work at it.", IsBookOfTheWeek = true, ImageThumbnailUrl = "https://www.safaribooksonline.com/library/cover/9780136083238/360h/" },
                     new Book { Name = "Refactoring", Price = 10.95M, ShortDescription = "Our famous Book!", LongDescription = "Even bad code can function. But if code isn’t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn’t have to be that way. Noted software expert Robert C.Martin presents a revolutionary paradigm with Clean Code: A Handbook of Agile Software Craftsmanship.Martin has teamed up with his colleagues from Object Mentor to distill their best agile practice of cleaning code “on the fly” into a book that will instill within you the values of a software craftsman and make you a better programmer—but only if you work at it.", IsBookOfTheWeek = true, ImageThumbnailUrl = "https://www.safaribooksonline.com/library/cover/9780134757681/360h/" },

                    new Book { Name = "Clean Code", Price = 20.95M, ShortDescription = "Our Refactoring Book!", LongDescription = "Even bad code can function. But if code isn’t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn’t have to be that way. Noted software expert Robert C.Martin presents a revolutionary paradigm with Clean Code: A Handbook of Agile Software Craftsmanship.Martin has teamed up with his colleagues from Object Mentor to distill their best agile practice of cleaning code “on the fly” into a book that will instill within you the values of a software craftsman and make you a better programmer—but only if you work at it.", IsBookOfTheWeek = true, ImageThumbnailUrl = "https://www.safaribooksonline.com/library/cover/9780136083238/360h/" },
                    new Book { Name = "Refactoring", Price = 10.95M, ShortDescription = "Our famous Book!", LongDescription = "Even bad code can function. But if code isn’t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn’t have to be that way. Noted software expert Robert C.Martin presents a revolutionary paradigm with Clean Code: A Handbook of Agile Software Craftsmanship.Martin has teamed up with his colleagues from Object Mentor to distill their best agile practice of cleaning code “on the fly” into a book that will instill within you the values of a software craftsman and make you a better programmer—but only if you work at it.", IsBookOfTheWeek = true, ImageThumbnailUrl = "https://www.safaribooksonline.com/library/cover/9780134757681/360h/" },

                    new Book { Name = "Clean Code", Price = 20.95M, ShortDescription = "Our Refactoring Book!", LongDescription = "Even bad code can function. But if code isn’t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn’t have to be that way. Noted software expert Robert C.Martin presents a revolutionary paradigm with Clean Code: A Handbook of Agile Software Craftsmanship.Martin has teamed up with his colleagues from Object Mentor to distill their best agile practice of cleaning code “on the fly” into a book that will instill within you the values of a software craftsman and make you a better programmer—but only if you work at it.", IsBookOfTheWeek = true, ImageThumbnailUrl = "https://www.safaribooksonline.com/library/cover/9780136083238/360h/" },
                    new Book { Name = "Refactoring", Price = 10.95M, ShortDescription = "Our famous Book!", LongDescription = "Even bad code can function. But if code isn’t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn’t have to be that way. Noted software expert Robert C.Martin presents a revolutionary paradigm with Clean Code: A Handbook of Agile Software Craftsmanship.Martin has teamed up with his colleagues from Object Mentor to distill their best agile practice of cleaning code “on the fly” into a book that will instill within you the values of a software craftsman and make you a better programmer—but only if you work at it.", IsBookOfTheWeek = true, ImageThumbnailUrl = "https://www.safaribooksonline.com/library/cover/9780134757681/360h/" },

                    new Book { Name = "Clean Code", Price = 20.95M, ShortDescription = "Our Refactoring Book!", LongDescription = "Even bad code can function. But if code isn’t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn’t have to be that way. Noted software expert Robert C.Martin presents a revolutionary paradigm with Clean Code: A Handbook of Agile Software Craftsmanship.Martin has teamed up with his colleagues from Object Mentor to distill their best agile practice of cleaning code “on the fly” into a book that will instill within you the values of a software craftsman and make you a better programmer—but only if you work at it.", IsBookOfTheWeek = true, ImageThumbnailUrl = "https://www.safaribooksonline.com/library/cover/9780136083238/360h/" }
);
            }
            context.SaveChanges();
        }

    }
}
